languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Sathyajith Bhat"
description = "Personal blog of Sathyajith"
copyright = "&copy; 2023 Sathyajith Bhat"

dateFormat = "2 January 2006"

[author]
  name = "Sathyajith Bhat"
  email = "sathya@sathyasays.com"
  # image = "img/author.jpg"
  headline = "Author, AWS Container Hero and DevOps Specialist"
  bio = "Staff Software Engineer at The Trade Desk"
  links = [
    { twitter = "https://twitter.com/sathyabhat" },
    { mastodon = "https://mastodon.social/sathyabhat" },
    { linkedin = "https://linkedin.com/in/sathyabhat" },
    { youtube = "https://youtube.com/sathyasjbhat" },
  ]
