# -- Markup --
# These settings are required for the theme to function.

[goldmark]
  [goldmark.renderer]
    hardWraps = true
    unsafe = true
    xHTML = true
[highlight]
  codeFences = true
  lineNos = true
  lineNumbersInTable = true
  noClasses = false
[tableOfContents]
  endLevel = 5
  ordered = false
  startLevel = 2