[[main]]
name              = "Home"
identifier        = "home"
url               = "/"
weight            = 1

[[main]]
name              = "About"
identifier        = "about"
url               = "/about/"
weight            = 2


[[main]]
name              = "Subscribe"
identifier        = "subscribe"
url               = "/subscribe"
weight            = 20

[[footer]]
name              = "Categories"
identifier        = "categories"
url               = "/categories/"
weight            = 4

[[footer]]
name              = "Tags"
identifier        = "tags"
url               = "/tags/"
weight            = 5

[[footer]]
name              = "All posts"
identifier        = "tags"
url               = "/tags/"
weight            = 5

[[footer]]
name              = "Tech Blog"
identifier        = "tech"
url               = "https://sathyasays.com/"
weight            = 10