local_backend: true

backend:
  name: git-gateway

media_folder: "images/uploads"

collections:
  - name: "weekly-notes" # Used in routes, e.g., /admin/collections/blog
    label: "Weekly Notes" # Used in the UI
    folder: "content/weekly-notes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "index.md" # Filename template, e.g., YYYY-MM-DD-title.md
    nested:
      depth: 100
    fields: # The fields for each document, usually in front matter
      - {
          label: "Categories",
          name: "categories",
          widget: "list",
          default: "weekly-notes",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
