---
label: Blog post
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: author
  label: author
- type: text
  name: type
  label: type
- type: datetime
  name: date
  label: date
- type: text
  name: url
  label: url
- name: featured_image
  type: text
  config:
    required: false
  label: featured image
- type: text
  name: description
  label: description
- type: list
  name: categories
  label: categories
- type: list
  name: tags
  label: tags
- name: meta_image
  type: text
  config:
    required: false
  label: meta_image
  description: Image to be used for social media previews
pages:
- content/a-look-back-at-2021.md
- content/exploring-romania-transylvania.md
- content/looking-back-at-the-last-5-years-at-adobe.md
- content/romania-transylvania-travelogue-bran-zarnesti.md
